apiVersion: v1
kind: Service
metadata:
  name: provider-service
spec:
  ports:
    - port: 5001
  selector:
    app: provider-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      labels:
        app: provider-service
    spec:
      containers:
        - name: provider-service
          image: migarad/provider-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/FoodGram
            - name: PORT
              value: "5001"
