spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/Micro-Service-user}
      database: Micro-Service
  application:
    name: user-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

# To integrate SonarCloud
sonar:
  projectKey: MigaraDenuwan_Service-Hub---Microservice-Project
  organization: migaradenuwan
  host.url: https://sonarcloud.io
