spring:
  data:
    mongodb:
      uri: mongodb+srv://it22143204:ZfTg6QRxfTY1Fgam@cluster0.any78ur.mongodb.net/Micro-Service-user?retryWrites=true&w=majority&appName=Cluster0
      database: Micro-Service
  application:
    name: user-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
