server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:it22143204@my.sliit.lk}
    password: ${MAIL_PASSWORD:yfholzvkfdikkkzy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# To integrate SonarCloud
sonar:
  projectKey: MigaraDenuwan_Service-Hub---Microservice-Project
  organization: migaradenuwan
  host.url: https://sonarcloud.io
