sonar.projectKey=MigaraDenuwan_Service-Hub---Microservice-Project
sonar.organization=migaradenuwan
sonar.host.url=https://sonarcloud.io

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=Backend,frontend/src
sonar.exclusions=**/node_modules/**,**/target/**,**/.mvn/**,**/mvnw**,**/mvnw.cmd,**/.git/**,**/Dockerfile,**/docker-compose.yml,**/k8s/**,**/frontend/node_modules/**,**/gateway-service/**

# Java specific configurations
sonar.java.binaries=**/target/classes

# Language specific settings
sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
sonar.sourceEncoding=UTF-8
