version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1238450
      POSTGRES_DB: appointments_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appointments_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/Micro-Service
      SPRING_APPLICATION_NAME: user-service
      SERVER_PORT: 8082

  provider-service:
    build: ./provider-service
    container_name: provider-service
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/FoodGram
      PORT: 5001

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
      provider-service:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1238450
      DB_NAME: appointments_db
      PROVIDER_SERVICE_URL: http://provider-service:5001
      PORT: 5002
      NODE_ENV: production

volumes:
  mongo-data:
  postgres-data:
